name: Publish SysPlant documentation
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Prepare docs using lazydocs
        run: |
          REPO_NAME=${{ github.repository }}
          REPO_NAME=${REPO_NAME#*/}
          REPO_NAME_LC=${REPO_NAME,,}
          echo "[+] Install plugins"
          pip install lazydocs mkdocs-awesome-pages-plugin
          export PYTHONPATH=$PWD
          echo "[+] Generate documentation of ${REPO_NAME_LC}/ using \"https://github.com/${{ github.repository }}/blob/master\" as base-url..."
          lazydocs --output-path="./docs/documentation" --overview-file="README.md" --src-base-url="https://github.com/${{ github.repository }}/blob/master" ${REPO_NAME_LC}/

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
